version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      timezone: Etc/UTC
      time: "00:00"
      day: sunday
    labels: [ignore]

    commit-message:
      include: scope
      prefix: chore
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      timezone: Etc/UTC
      time: "00:00"
      day: sunday
    labels: [ignore]
    commit-message:
      include: scope
      prefix: chore
