version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      timezone: Etc/UTC
      time: "14:20"
    labels: [ignore]
    commit-message:
      include: scope
      prefix: chore
