version: 2
updates:
  - package-ecosystem: Gradle
    directory: /
    schedule:
      interval: daily
      timezone: Etc/UTC
      time: 14:05
      day: sunday
    labels: [ignore]
    commit-message:
      include: scope
      prefix: chore
