comment:
  layout: "diff, files"
  behavior: default
  require_changes: false
coverage:
  status:
    project:
      default:
        if_ci_failed: success
    patch: false
ignore:
  - "8vim/src/main/kotlin/inc/flide/vim8/app"
  - "8vim/src/main/kotlin/inc/flide/vim8/datastore/ui"
  - "8vim/src/main/kotlin/inc/flide/vim8/datastore/Datastore.kt"
  - "8vim/src/main/kotlin/inc/flide/vim8/lib"
  - "8vim/src/main/kotlin/inc/flide/vim8/theme/Theme.kt"
  - "8vim/src/main/kotlin/inc/flide/vim8/models/error/LayoutError.kt"
  - "8vim/src/main/kotlin/inc/flide/vim8/VIM8Application.kt"
  - "8vim/src/main/kotlin/inc/flide/vim8/PreferenceDataAdapter.kt"
  - "8vim/src/main/kotlin/inc/flide/vim8/Vim8ImeService.kt"
  - "8vim/src/main/kotlin/inc/flide/vim8/LifecycleInputMethodService.kt"
  - "8vim/src/main/kotlin/inc/flide/vim8/clipboard/*Layout.kt"
  - "8vim/src/main/kotlin/inc/flide/vim8/keyboard/**/*Layout.kt"
  - "8vim/src/main/kotlin/inc/flide/vim8/ime/ui/floating/compose"
  - "8vim/src/main/kotlin/inc/flide/vim8/ime/ui/**/*Layout.kt"
  - "8vim/src/main/kotlin/inc/flide/vim8/AppPrefs.kt"
