[versions]
# Main
android-gradle-plugin = "8.0.2"
android-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-lifecycle = "2.6.1"
androidx-preference = "1.2.0"
android-material = "1.9.0"
android-recyclerview = "1.3.0"
apache-commons = "1.7"
colorpreference = "1.1.0"
jackson = "2.13.5"
json-schema-validator = "1.0.75"
keyboardview = "0.0.2"
kotlin = "1.8.22"
logback-android = "3.0.0"
mannodermaus-android-junit5 = "1.9.3.0"
material-dialog = "3.3.0"
slf4j = "2.0.7"

# Testing
androidx-test-core = "1.5.0"
androidx-test-ext = "1.1.5"
androidx-test-runner = "1.5.2"
androidx-test-espresso = "3.5.1"
assertj = "3.24.2"
jqwik = "1.7.3"
junit4 = "4.13.2"
junit5 = "5.9.3"
logback-classic = "1.2.11"
mockito = "5.3.1"

[libraries]
# Main
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "android-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "android-recyclerview" }
material-dialog-core = { module = "com.afollestad.material-dialogs:core", version.ref = "material-dialog" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
colorpreference = { module = "com.github.kizitonwose.colorpreference:support", version.ref = "colorpreference" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logback-android" }
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "json-schema-validator" }
keyboardview = { module = "io.github.hijamoya:keyboardview", version.ref = "keyboardview" }
apache-commons-text = { module = "org.apache.commons:commons-text", version.ref = "apache-commons" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# Testing
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-ext = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit5 = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

[plugins]
# Main
agp-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
mannodermaus-android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "mannodermaus-android-junit5" }