# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build"
  lane :build do
    gradle(task: "clean assembleRelease")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Verify if the version is getting updated"
  lane :versionUpdate do
    currentVersionCode = android_get_version_code(
      gradle_file: "8vim/build.gradle" # optional
    )
    android_set_version_name(
      version_name: "iteration-" + (currentVersionCode.to_i + 1).to_s,
      gradle_file: "8vim/build.gradle" # optional
    )
    android_set_version_code(
      version_code: currentVersionCode.to_i + 1,
      gradle_file: "8vim/build.gradle" # optional
    )
      commit_android_version_bump(
        gradle_file_folder:"8vim"
      )
  end
end
