name: Android Pre Release

on:
  push:
    branches: [ prerelease ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
          cache: gradle
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > 8vim/8vim.jks
      - name: Build APK
        env:
          VIM8_BUILD_KEYSTORE_FILE: ./8vim.jks
          VIM8_BUILD_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          VIM8_BUILD_KEY_ALIAS:  ${{ secrets.ALIAS }}
          VIM8_BUILD_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease
      - name: Google play release
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: inc.flide.vi8
          releaseFiles: 8vim/build/outputs/apk/release/8vim-release.apk
          track: internal
          status: inProgress
          whatsNewDirectory: distribution/whatsnew
          mappingFile: 8vim/build/outputs/mapping/release/mapping.txt