name: Android CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle
      - name: Test with Gradle
        run: ./gradlew checkstyle lint test assembleDebug
      - name: Upload artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: 8vim-debug
          path: 8vim/build/outputs/apk/debug/8vim-debug.apk
          retention-days: 7
      - name: Save PR number
        if: github.event_name == 'pull_request'
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v3
        if: github.event_name == 'pull_request'
        with:
          name: pr_number
          path: pr/
