name: Android Release

on:
  push:
    tags: ["iteration-*"]

jobs:
  release:
    name: Deploy the app to Google playstore and create a release
    permissions:
      actions: read
      issues: read
      pull-requests: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: gradle
      - name: Setup env
        run: |
          set +a
          . ./8vim/version.properties
          set -a
          mkdir -p distribution/whatsnew
          cp metadata/en-US/changelogs/${VERSION_CODE}.txt distribution/whatsnew/whatsnew-en-US
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" > keystore-b64.txt
          base64 -d keystore-b64.txt > 8vim/8vim.jks
      - name: Build APK/AAB
        env:
          VIM8_BUILD_KEYSTORE_FILE: ./8vim.jks
          VIM8_BUILD_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          VIM8_BUILD_KEY_ALIAS: ${{ secrets.ALIAS }}
          VIM8_BUILD_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease bundleRelease
      - name: Google play release
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: inc.flide.vi8
          releaseFiles: |
            8vim/build/outputs/apk/release/8vim-release.apk
            8vim/build/outputs/bundle/release/8vim-release.aab
          track: internal
          whatsNewDirectory: distribution/whatsnew
          mappingFile: 8vim/build/outputs/mapping/release/mapping.txt
      - name: Create Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: changelog-configuration.json
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            8vim/build/outputs/apk/release/8vim-release.apk
            8vim/build/outputs/bundle/release/8vim-release.aab
  unrelease:
    name: Unrelease if an error happened
    needs: [release]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{failure()}}
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          tag_name: ${{github.ref_name}}
          github_token: ${{ secrets.PAT }}
