name: Android CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle
      - name: Test with Gradle
        run: ./gradlew checkstyle lint test assembleDebug
      - name: Upload artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: 8vim-debug-${{github.event.pull_request.id}}
          path: 8vim/build/outputs/apk/debug/8vim-debug.apk
          retention-days: 7
      - name: Get artifact link
        if: github.event_name == 'pull_request'
        id: artifact
        run: |
          curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -s \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{github.run_id}}" \
          | jq -r '{"check_suite_id": .check_suite_id, "artifacts_url": .artifacts_url}' > run.json
          cat run.json
          check_suite_id=$(jq -j '.check_suite_id' run.json)
          artifacts_url=$(jq -j '.artifacts_url' run.json)

          curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -s \
          ${artifacts_url} \
          | jq -j '.artifacts[0]' > artifact.json

          echo "url=https://github.com/flide/8VIM/suites/${check_suite_id}/artifacts/$(jq -j '.id' artifact.json)" >> $GITHUB_OUTPUT
          echo "expires=$(jq -j '.expires_at' artifact.json)" >> $GITHUB_OUTPUT
      - name: Update comment
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Artifact [8vim-debug-${{github.event.pull_request.id}}](${{steps.artifact.outputs.url}}) available until: ${{steps.artifact.outputs.expires}}
          comment_tag: artifact
