name: Run checkstyle,lint and coverage
on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        default: false
jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - run: ./gradlew check
      - name: Upload coverage reports to Codecov
        if: github.triggering_actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v3
        with:
          directory: ./8vim/build/reports/jacoco/jacocoTestReportDebug
          flags: unit
