name: Run checkstyle,lint and coverage
on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        default: false
      skip-codecov:
        type: boolean
        default: false
jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - run: ./gradlew check
      - name: Upload coverage reports to Codecov
        if: ${{ !inputs.skip-codecov }}
        uses: codecov/codecov-action@v3
        with:
          directory: ./8vim/build/reports/jacoco/jacocoTestReportDebug
          flags: unit
