name: Run checkstyle,lint and coverage
on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        default: false
      skip-codecov:
        type: boolean
        default: false
jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "19"
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew check
      - name: Upload coverage reports to Codecov
        if: ${{ !inputs.skip-codecov }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./8vim/build/reports/jacoco/jacocoTestReportDebug
