name: Discord notification release

on:
  release:
    types: [created]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notify
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            New release: ${{github.event.release.name}}
            ${{github.event.release.html_url}}
