name: Extract version
on:
  workflow_call:
    outputs:
      major:
        value: ${{jobs.version.outputs.major}}
      minor:
        value: ${{jobs.version.outputs.minor}}
      patch:
        value: ${{jobs.version.outputs.patch}}
      rc:
        value: ${{jobs.version.outputs.rc}}
      version_code:
        value: ${{jobs.version.outputs.version_code}}
      version_name:
        value: ${{jobs.version.outputs.version_name}}
jobs:
  version:
    name: Get app version
    runs-on: ubuntu-latest
    outputs:
      major: ${{steps.vars.outputs.major}}
      minor: ${{steps.vars.outputs.minor}}
      patch: ${{steps.vars.outputs.patch}}
      rc: ${{steps.vars.outputs.rc}}
      version_code: ${{steps.vars.outputs.version_code}}
      version_name: ${{steps.vars.outputs.version_name}}
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: vars
        run: |
          set +a
          . ./8vim/version.properties
          set -a
          RC_CODE=0
          if [ $RC -gt 0 ]
          then
            echo "version_name=$MAJOR.$MINOR.$PATCH-rc.$RC" >> $GITHUB_OUTPUT
            RC_CODE=$((100-$RC))
          else
            echo "version_name=$MAJOR.$MINOR.$PATCH" >> $GITHUB_OUTPUT
          fi

          echo "major=$MAJOR" >> $GITHUB_OUTPUT
          echo "minor=$MINOR" >> $GITHUB_OUTPUT
          echo "patch=$PATCH" >> $GITHUB_OUTPUT
          echo "rc=$RC" >> $GITHUB_OUTPUT
          echo "version_code=$(( 1000000 * $MAJOR + 10000 * $MINOR + 100 * $PATCH - $RC_CODE))" >> $GITHUB_OUTPUT
