name: Extract version
on:
  workflow_call:
    outputs:
      major:
        value: ${{jobs.version.outputs.major}}
      minor:
        value: ${{jobs.version.outputs.minor}}
      patch:
        value: ${{jobs.version.outputs.patch}}
      rc:
        value: ${{jobs.version.outputs.rc}}
      version_code:
        value: ${{jobs.version.outputs.version_code}}
      version_name:
        value: ${{jobs.version.outputs.version_name}}
jobs:
  version:
    name: Get app version
    runs-on: ubuntu-latest
    outputs:
      major: ${{steps.vars.outputs.major}}
      minor: ${{steps.vars.outputs.minor}}
      patch: ${{steps.vars.outputs.patch}}
      rc: ${{steps.vars.outputs.rc}}
      version_code: ${{steps.vars.outputs.version_code}}
      version_name: ${{steps.vars.outputs.version_name}}
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: vars
        run: |
          set +a
          . ./8vim/version.properties
          set -a
          echo "major=$MAJOR" >> $GITHUB_OUTPUT
          echo "minor=$MINOR" >> $GITHUB_OUTPUT
          echo "patch=$PATCH" >> $GITHUB_OUTPUT
          echo "rc=$RC" >> $GITHUB_OUTPUT
          echo "version_code=$(( 1000000 * $MAJOR + 10000 * $MINOR + 100 * $PATCH - $RC))" >> $GITHUB_OUTPUT
          echo "version_name=$MAJOR.$MINOR.$PATCH" >> $GITHUB_OUTPUT
