name: Matrix notification issues

on:
  issues:
    types: [opened, closed, reopened]

jobs:
  notify:
    name: Matrix notification issues
    uses: ./.github/workflows/matrix-notify.yaml
    with:
      message: |
        [${{github.event.issue.state}}] Issue #${{github.event.issue.number}} by ${{github.event.issue.user.login}}
        ${{github.event.issue.html_url}}
    secrets: inherit
