name: Merged pull request

concurrency: release

on:
  pull_request_target:
    branches: [master]
    types: [closed]
    paths:
      - "gradle/libs.versions.toml"
      - "**.gradle.kts"
      - "8vim/**"
jobs:
  changes:
    if: ${{ github.event_name=='pull_request_target' && github.event.pull_request.merged == true }}
    name: Detect changed files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - '8vim/**/*.java'
              - '8vim/**/*.kt'
              - '8vim/**/*.xml'
              - '8vim/**/*.pro'
              - '**.gradle'
              - '**.gradle.kts'
              - 'gradle/libs.versions.toml'
              - '8vim/src/main/res/raw/*.yaml'
              - '8vim/src/main/res/raw/*.yml'
              - modified: '8vim/src/main/resources/schema.json'
  bump_version:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    name: Update version
    uses: ./.github/workflows/bump-version.yaml
    with:
      message: ${{github.event.pull_request.title}}
      version: rc
    secrets: inherit
  release:
    needs: [bump_version]
    name: Release
    uses: ./.github/workflows/publish.yaml
    with:
      version_code: ${{needs.bump_version.outputs.version_code}}
      version_name: ${{needs.bump_version.outputs.version_name}}
    secrets: inherit
    permissions:
      actions: read
      issues: read
      pull-requests: read
      contents: write
