name: Update PR comment

on:
  workflow_run:
    workflows: [PR test]
    types: [completed]
    branches-ignore: ["dependabot/**"]
jobs:
  update_pr_comment:
    permissions:
      actions: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get artifact link
        id: artifact
        run: |
          curl \
          -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -s \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{github.event.workflow_run.id}}/artifacts" \
          | jq -c '.artifacts[0]' > artifact.json

          [[ $(jq -j '.name' artifact.json)  = "artifact-debug" ]] && exit 0

          pr_number=$(curl \
          -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Authorization: Bearer ${{ github.token }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{github.event.workflow_run.id}}" \
          -s \
          | jq -j '.referenced_workflows[0].ref' | cut -d '/' -f 3)

          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
          echo "url=https://github.com/${{ github.repository }}/actions/runs/${{github.event.workflow_run.id}}/artifacts/$(jq -j '.id' artifact.json)" >> $GITHUB_OUTPUT
          echo "expires=$(jq -j '.expires_at' artifact.json)" >> $GITHUB_OUTPUT
      - name: Update comment
        if: ${{steps.artifact.outputs.expires != 'null' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Artifact [8vim-debug](${{steps.artifact.outputs.url}}) available until: ${{steps.artifact.outputs.expires}}
          comment_tag: artifact
          pr_number: ${{steps.artifact.outputs.pr_number}}
