name: PR test

concurrency: pr-${{github.event.number}}

on:
  pull_request:
    branches: [master]
    paths:
      - "metadata/**/changelogs/*.txt"
      - "**.gradle"
      - "8vim/**"
jobs:
  changes:
    name: Detect changed files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      src: ${{ steps.changes.outputs.src }}
      yaml: ${{ steps.changes.outputs.yaml }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            metadata:
              - 'metadata/**/changelogs/*.txt'
            src:
              - '8vim/**/*.java'
              - '8vim/**/*.kt'
              - '8vim/**/*.xml'
              - '8vim/**/*.pro'
              - '**.gradle'
            yaml:
              - '8vim/src/main/res/raw/*.yaml'
              - '8vim/src/main/res/raw/*.yml'
              - '8vim/src/main/res/values/strings.xml'
              - modified: '8vim/src/main/resources/schema.json'
      - if: ${{ steps.changes.outputs.metadata == 'true' }}
        run: |
          echo "You cannot change the changelogs manually"
          exit 1
  validate_layouts:
    needs: changes
    if: ${{ needs.changes.outputs.yaml == 'true' }}
    name: Validate language layouts
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: mavrosxristoforos/get-xml-info@1.1.1
        id: xml
        with:
          xml-file: 8vim/src/main/res/values/strings.xml
          xpath: //resources/string-array[@name='keyboard_layouts_id']/item
      - uses: actions/github-script@v6
        env:
          XML: ${{steps.xml.outputs.info}}
        with:
          script: |
            let failed = false
            const xml = process.env.XML.split(',')
            for(const lang of xml) {
              const pattern = [`8vim/src/main/res/raw/${lang}.yaml`,`8vim/src/main/res/raw/${lang}.yml`]
              const globber = await glob.create(pattern.join("\n"))
              const files = await globber.glob()
              if(files.length!=1) {
                core.error(`Missing language layout for ${lang}`)
                failed = true
              }
            }
            if(failed) {
              core.setFailed("Missing layout files")
            }
      - uses: 8VIM/json-yaml-validate@main
        with:
          json_schema: ./8vim/src/main/resources/schema.json
          yaml_as_json: "true"
          base_dir: ./8vim/src/main/res/raw
  test:
    name: 8VIM tests
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: gradle
      - run: ./gradlew check
  build:
    if: ${{ !cancelled() && (needs.test.result == 'success' || needs.validate_layouts.result == 'success') }}
    needs: [validate_layouts, test]
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{github.ref}}
      target: debug
    secrets: inherit
  upload_artifact:
    if: ${{ !cancelled() && needs.build.result=='success' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.number }} > ./pr_number
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: pr_number
          retention-days: 7
