name: PR test

concurrency: pr-${{github.event.number}}

on:
  pull_request:
    branches: [master]
    paths:
      - "metadata/**/changelogs/*.txt"
      - "**.gradle"
      - "8vim/**"
jobs:
  changes:
    name: Detect changed files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      src: ${{ steps.changes.outputs.src }}
      yaml: ${{ steps.changes.outputs.yaml }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            metadata:
              - 'metadata/**/changelogs/*.txt'
            src:
              - '8vim/**/*.java'
              - '8vim/**/*.kt'
              - '8vim/**/*.xml'
              - '8vim/**/*.pro'
              - '**.gradle'
              - '**.gradle.kts'
              - 'gradle/libs.version.toml'
            yaml:
              - '8vim/src/main/res/raw/*.yaml'
              - '8vim/src/main/res/raw/*.yml'
              - modified: '8vim/src/main/resources/schema.json'
      - if: ${{ steps.changes.outputs.metadata == 'true' }}
        run: |
          echo "You cannot change the changelogs manually"
          exit 1
  validate_layouts:
    needs: changes
    if: ${{ needs.changes.outputs.yaml == 'true' }}
    name: Validate language layouts
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: 8VIM/json-yaml-validate@main
        with:
          json_schema: ./8vim/src/main/resources/schema.json
          yaml_as_json: "true"
          base_dir: ./8vim/src/main/res/raw
  test:
    name: 8VIM tests
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    uses: ./.github/workflows/codecheck.yaml
    secrets: inherit
  build:
    if: ${{ !cancelled() && (needs.test.result == 'success' || needs.validate_layouts.result == 'success') }}
    needs: [validate_layouts, test]
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{github.ref}}
      target: debug
    secrets: inherit
  upload_artifact:
    if: ${{ !cancelled() && needs.build.result=='success' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.number }} > ./pr_number
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: pr_number
          retention-days: 7
