name: PR test

concurrency: pr-${{github.event.number}}

on:
  pull_request:
    branches: [master]

jobs:
  dependabot_check:
    if: |
      contains(github.event.pull_request.labels.*.name, 'ignore') 
        && startsWith(github.head_ref, 'dependabot/gradle')
    uses: ./.github/workflows/codecheck.yaml
    with:
      skip-codecov: true
    secrets: inherit
  commit:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ignore') }}
    outputs:
      msg: ${{steps.commit.outputs.msg}}
      previous: ${{steps.commit.outputs.previous}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: commit
        run: |
          echo "msg=$(git show -s --format=%s)" >> $GITHUB_OUTPUT
          echo "previous=$(git rev-parse HEAD^)" >> $GITHUB_OUTPUT
  changes:
    name: Detect changed files
    runs-on: ubuntu-latest
    needs: [commit]
    permissions:
      pull-requests: read
    outputs:
      src: ${{ steps.changes.outputs.src }}
      yaml: ${{ steps.changes.outputs.yaml }}
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: ${{needs.commit.outputs.previous}}
          filters: |
            metadata:
              - 'metadata/**/changelogs/*.txt'
            src:
              - '8vim/**/*.java'
              - '8vim/**/*.kt'
              - '8vim/**/*.xml'
              - '8vim/**/*.pro'
              - '**.gradle'
              - '**.gradle.kts'
              - 'gradle/libs.versions.toml'
            yaml:
              - '8vim/src/main/res/raw/*.yaml'
              - '8vim/src/main/res/raw/*.yml'
              - '8vim/src/main/resources/schemas/**/*.json'
            schemas:
              - '8vim/src/main/resources/schemas/**/*.json'
      - if: ${{ steps.changes.outputs.metadata == 'true' }}
        run: |
          echo "You cannot change the changelogs manually"
          exit 1
  validate_layouts:
    needs: changes
    if: ${{ needs.changes.outputs.yaml == 'true' }}
    name: Validate language layouts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 8VIM/json-yaml-validate@main
        with:
          schema_dir: ./8vim/src/main/resources/schemas
          schema_name: https://8vim.github.io/schemas/schema.json
          base_dir: ./8vim/src/main/res/raw
  test_run:
    name: Test & coverage
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    uses: ./.github/workflows/codecheck.yaml
    secrets: inherit
  build:
    needs: [validate_layouts, test_run, commit]
    if: |
      !cancelled() && (
        (needs.test_run.result != 'skipped' 
          && needs.validate_layouts.result != 'skipped' 
          && needs.test_run.result == 'success' 
          && needs.validate_layouts.result == 'success')
        || (needs.test_run.result == 'skipped'
          && needs.validate_layouts.result == 'success')
        || (needs.validate_layouts.result == 'skipped' 
          && needs.test_run.result == 'success')
      )
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{github.ref}}
      target: debug
      pr: ${{github.event.number}}
      sha: ${{github.event.pull_request.head.sha}}
      commit: "${{needs.commit.outputs.msg}}"
    secrets: inherit
  test_check:
    name: Github action test check workaround
    if: ${{always()}}
    needs: [validate_layouts, test_run]
    runs-on: ubuntu-latest
    steps:
      - run: exit ${{ ((needs.validate_layouts.result == 'skipped' && needs.test_run.result == 'skipped') || (needs.test_run.result != 'failure' && needs.validate_layouts.result != 'failure')) && '0' || '1' }}