name: PR test

concurrency: pr-${{github.event.number}}

on:
  pull_request:
    branches: [master]
    paths:
      - "metadata/**/changelogs/*.txt"
      - "gradle/libs.version.toml"
      - "**.gradle"
      - "**.gradle.kts"
      - "8vim/**"
jobs:
  changes:
    name: Detect changed files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    if: github.actor != 'dependabot[bot]'
    outputs:
      src: ${{ steps.changes.outputs.src }}
      yaml: ${{ steps.changes.outputs.yaml }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            metadata:
              - 'metadata/**/changelogs/*.txt'
            src:
              - '8vim/**/*.java'
              - '8vim/**/*.kt'
              - '8vim/**/*.xml'
              - '8vim/**/*.pro'
              - '**.gradle'
              - '**.gradle.kts'
              - 'gradle/libs.version.toml'
            yaml:
              - '8vim/src/main/res/raw/*.yaml'
              - '8vim/src/main/res/raw/*.yml'
              - modified: '8vim/src/main/resources/schema.json'
      - if: ${{ steps.changes.outputs.metadata == 'true' }}
        run: |
          echo "You cannot change the changelogs manually"
          exit 1
  validate_layouts:
    needs: changes
    if: ${{ needs.changes.outputs.yaml == 'true' }}
    name: Validate language layouts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 8VIM/json-yaml-validate@use-multiple-schemas
        with:
          schema_dir: ./8vim/src/main/resources/schemas
          schema_name: https://8vim.github.io/schemas/schema.json
          yaml_as_json: "true"
          base_dir: ./8vim/src/main/res/raw
  test_run:
    name: 8VIM tests
    needs: changes
    if: ${{ github.actor == 'dependabot[bot]' || needs.changes.outputs.src == 'true' }}
    uses: ./.github/workflows/codecheck.yaml
    secrets: inherit
  test_check:
    name: Github action test check workaround
    if: ${{always()}}
    needs: test_run
    runs-on: ubuntu-latest
    steps:
      - run: exit ${{ needs.test_run.result == 'success' && '0' || '1' }}
  build:
    if: ${{ github.actor != 'dependabot[bot]' && !cancelled() && (needs.test_check.result == 'success' || needs.validate_layouts.result == 'success') }}
    needs: [validate_layouts, test_check]
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{github.ref}}
      target: debug
    secrets: inherit
