name: Update private F-droid repo

on:
  workflow_call:
    inputs:
      type:
        type: string
        required: true
      tag:
        type: string
        default: ""
      pr:
        type: number
        default: -1
      artifact:
        type: number
        default: -1
      sha:
        type: string
        default: ""

env:
  DISPATCH_URL: https://api.github.com/repos/8VIM/fdroid/dispatches

jobs:
  fail:
    name: None valid type
    runs-on: ubuntu-latest
    if: ${{ !contains(fromJson(vars.FRDOID_TRIGGER_TYPE), inputs.type) }}
    steps:
      - run: exit 1
  rc:
    name: Update repo from RC
    runs-on: ubuntu-latest
    if: ${{  inputs.type == 'rc' }}
    steps:
      - name: check tag
        if: ${{ !startsWith(inputs.tag,'v') }}
        run: exit 1
      - run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.PAT}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          $DISPATCH_URL \
          -d '{"event_type":"rc","client_payload":{"tag": "${{inputs.tag}}"}}'

  pr:
    name: Update repo from PR
    runs-on: ubuntu-latest
    if: ${{  inputs.type == 'pr' }}
    steps:
      - name: check tag
        if: ${{ inputs.pr < 0 || inputs.artifact < 0 || inputs.sha == ''}}
        run: exit 1
      - run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.PAT}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          $DISPATCH_URL \
          -d '{"event_type":"pr","client_payload":{"pr": ${{inputs.pr}}, "artifact": ${{inputs.artifact}}, "sha": "${{inputs.sha}}"}}'

  merge:
    name: Update repo on merge
    runs-on: ubuntu-latest
    if: ${{  inputs.type == 'merge' }}
    steps:
      - name: check tag
        if: ${{ inputs.pr < 0 }}
        run: exit 1
      - run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.PAT}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          $DISPATCH_URL \
          -d '{"event_type":"merge","client_payload":{"pr": ${{inputs.pr}}}}'
