name: Release
run-name: |
  Releasing 8VIM with next version: ${{inputs.version}}
concurrency: release
on:
  workflow_dispatch:
    inputs:
      whatsnew:
        required: true
        description: Store release message
      version:
        required: true
        default: minor
        type: choice
        options:
          - major
          - minor
          - patch
        description: Next version
jobs:
  update_version:
    name: Update app version
    uses: ./.github/workflows/bump-version.yaml
    with:
      message: ${{github.event.inputs.whatsnew}}
      version: next
    secrets: inherit
  next_version:
    needs: update_version
    name: Next version
    uses: ./.github/workflows/bump-version.yaml
    with:
      version: ${{github.event.inputs.version}}
    secrets: inherit
